Init release
eora-ai/visionhub-cli pull request #2
Opened 2021-03-16 13:39 UTC by AndreyChertckov

Add base commands:
- login
- create
- build
- push
- deploy
- release

2021-03-22 10:06 UTC, VladVin commented on visionhub-cli/src/config-template.yaml
> +  required: False
Похоже косты надо дефолтными ставить. Давай сделаем:
- 1 кредит за IMG2IMG
- 10 кредитов за IMG2VID, VID2IMG, VID2VID

И надо убрать возможность конфигурировать их со стороны пользователя

2021-03-22 10:06 UTC, VladVin commented on visionhub-cli/src/controllers.py
> +def build(directory: Path, config_path: Path):
Все хорошо, но не хватает прогона в `TEST_MODE`, см. [документацию](https://www.visionhub.ru/developer/docs#testirovanie)

2021-03-22 10:51 UTC, VladVin requested changes

2021-03-22 10:51 UTC, VladVin commented on visionhub-cli/src/config-template.yaml
> +version:
Предлагаю здесь ставить по умолчанию всегда последнюю версию, в данном случае v4

2021-03-22 10:51 UTC, VladVin commented on visionhub-cli/src/config-template.yaml
> +  description: Image input example
Предлагаю такие описания:
`Path to image input example`
`Path to video input example`
`Path to image output example`
`Path to video output example`

2021-03-22 10:51 UTC, VladVin commented on visionhub-cli/src/config-template.yaml
> +  description: Is model running on a gpu
`Does the model require GPU for running?`

2021-03-22 10:51 UTC, VladVin commented on visionhub-cli/src/config-template.yaml
> +  description: Size of the batch
`Maximum batch size that can fit to 13Gb of GPU memory`

2021-03-22 10:51 UTC, VladVin commented on visionhub-cli/src/config-template.yaml
> +is_video_stateful:
Если дан режим IMG2*, то этот параметр не нужно указывать (аналогично примерам фото/видео)

2021-03-22 10:51 UTC, VladVin commented on visionhub-cli/src/config-template.yaml
> +prediction_example:
Предлагаю сделать это поле обязательным, поскольку конечные пользователи модели должны иметь представление, что на выходе модели

2021-03-22 10:51 UTC, VladVin commented on visionhub-cli/src/controllers.py
> +            files[field] = open(config[field], "rb")
Надо файл закрыть

2021-03-22 10:51 UTC, VladVin commented on visionhub-cli/src/config-template.yaml
> +link:
Предлагаю собирать ссылку как `"public.registry.visionhub.ru/models/" + slug_name + ":" + version`

2021-03-22 17:53 UTC, AndreyChertckov commented on visionhub-cli/src/config-template.yaml
> +version:
Эта версия не связанна с нашими версиями, это нужно для версионирования со стороны пользователя

2021-03-25 12:30 UTC, gafmn commented
Если вводишь мод только IMG2IMG,  так и должно быть, что запрос идет на цену модели с мода IMG2VID?

2021-03-29 15:02 UTC, merged